# -*- coding: utf-8 -*-
"""Variabel.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1X4hftDp5RfehK-nUT0uSgkgTzz5Zp3NO
"""



"""# Membuat Variabel"""

a = 10 #artinya saya memasukkan 10 kedalam a
print(a)
#print merupakan cara untuk mengeluarkan nilai tersebut

x = 1000

"""# Hal-Hal yang perlu diperhatikan saat membuat variabel

memasukkan variabel teks, jika kita ingin memasukkan variabel berupa teks maka kita perlu menambahkan tanda petik
"""

y = "bla bla"
print(y)

"""Selain itu saat kita ingin medeklarasikan variabel tidak boleh didahului oleh anagka"""

10juta = 1000000000 #ini merupakan contoh yang salah

juta10 = 10000000 #ini merupakan cara yang dapat dilakukan untuk mengakalinya

"""Selain tidak boleh mengawali dengan angka, pendeklarasian variabel juga tidak boleh memakai spasi. namun cara ini dapat diakali dengan mengganti spasi dengan ("_"), itu merupakan cara yang paling populer digunakan"""

variabel y = 1020109100 #ini merupakan contoh yang salah

variabel_y = 101028120129 # ini merupakan contoh yang benar

"""# Mengganti Nilai variabel"""

a = 10
print ("nilai a =", a)

a = 20 #cukup mendeklarasikan variabel tersebut dengan nilai yang baru maka nilainya akan otomatis berganti dengan nilai yang terbaru yang ditulis
print("nilai a =", a)